version: '3.8'
services:
  gateway2:
    image: disterbia94/daf-gateway:latest
    environment:
      - TZ=Asia/Seoul
    ports:
      - "40000:40000"
    depends_on:
      - coach
# ...
  coach:
    image: disterbia94/daf-coach-service:latest
    environment:
      - TZ=Asia/Seoul

networks:
  default:
    name: my-network2