// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get-recommend": {
            "get": {
                "description": "회원별 추천운동 조회시 호출",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "회원별 운동추천  /daf"
                ],
                "summary": "회원별 운동추천",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "추천운동",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/core.RecomendResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/get-user-daf": {
            "get": {
                "description": "회원 신체능력 조회시 호출",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "회원 신체능력 조회  /daf"
                ],
                "summary": "회원 신체능력 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "신체능력 정보",
                        "schema": {
                            "$ref": "#/definitions/core.UserJointActionResponse"
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/set-user-daf": {
            "post": {
                "description": "회원 신체능력 설정시 호출",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "회원 신체능력 설정  /daf"
                ],
                "summary": "회원 신체능력 설정",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {jwt_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "요청 DTO - 업데이트 할 데이터",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/core.UserJointActionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "성공시 200 반환",
                        "schema": {
                            "$ref": "#/definitions/core.BasicResponse"
                        }
                    },
                    "400": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "요청 처리 실패시 오류 메시지 반환",
                        "schema": {
                            "$ref": "#/definitions/core.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "core.BasicResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "core.ErrorResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                }
            }
        },
        "core.ExerciseResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "core.RecomendResponse": {
            "type": "object",
            "properties": {
                "first": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core.ExerciseResponse"
                    }
                },
                "second": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/core.ExerciseResponse"
                    }
                }
            }
        },
        "core.UserJointActionRequest": {
            "type": "object",
            "properties": {
                "lla": {
                    "type": "string"
                },
                "llh": {
                    "type": "string"
                },
                "llk": {
                    "type": "string"
                },
                "llt": {
                    "type": "string"
                },
                "lra": {
                    "type": "string"
                },
                "lrh": {
                    "type": "string"
                },
                "lrk": {
                    "type": "string"
                },
                "lrt": {
                    "type": "string"
                },
                "tr": {
                    "type": "string"
                },
                "ule": {
                    "type": "string"
                },
                "ulf": {
                    "type": "string"
                },
                "uls": {
                    "type": "string"
                },
                "ulw": {
                    "type": "string"
                },
                "ure": {
                    "type": "string"
                },
                "urf": {
                    "type": "string"
                },
                "urs": {
                    "type": "string"
                },
                "urw": {
                    "type": "string"
                }
            }
        },
        "core.UserJointActionResponse": {
            "type": "object",
            "properties": {
                "lla": {
                    "type": "string"
                },
                "llav": {
                    "type": "string"
                },
                "llh": {
                    "type": "string"
                },
                "llk": {
                    "type": "string"
                },
                "llt": {
                    "type": "string"
                },
                "lra": {
                    "type": "string"
                },
                "lrav": {
                    "type": "string"
                },
                "lrh": {
                    "type": "string"
                },
                "lrk": {
                    "type": "string"
                },
                "lrt": {
                    "type": "string"
                },
                "tr": {
                    "type": "string"
                },
                "ulav": {
                    "type": "string"
                },
                "ule": {
                    "type": "string"
                },
                "ulf": {
                    "type": "string"
                },
                "uls": {
                    "type": "string"
                },
                "ulw": {
                    "type": "string"
                },
                "urav": {
                    "type": "string"
                },
                "ure": {
                    "type": "string"
                },
                "urf": {
                    "type": "string"
                },
                "urs": {
                    "type": "string"
                },
                "urw": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
