definitions:
  core.ErrorResponse:
    properties:
      err:
        type: string
    type: object
  core.ExerciseResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  core.RecomendResponse:
    properties:
      first:
        items:
          $ref: '#/definitions/core.ExerciseResponse'
        type: array
      second:
        items:
          $ref: '#/definitions/core.ExerciseResponse'
        type: array
    type: object
info:
  contact: {}
paths:
  /get-recommend:
    get:
      consumes:
      - application/json
      description: 회원별 추천운동 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 카테고리아이디:추천운동
          schema:
            additionalProperties:
              $ref: '#/definitions/core.RecomendResponse'
            type: object
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 회원별 운동추천
      tags:
      - 회원별 운동 /daf
swagger: "2.0"
