definitions:
  core.AutoLoginRequest:
    properties:
      device_id:
        type: string
      fcm_token:
        type: string
    type: object
  core.BasicResponse:
    properties:
      code:
        type: string
    type: object
  core.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  core.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  core.SignInRequest:
    properties:
      addr:
        type: string
      addr_detail:
        type: string
      birth:
        example: yyyy-mm-dd
        type: string
      disable_type:
        type: integer
      email:
        type: string
      gender:
        type: boolean
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      sns_id:
        type: string
      username:
        type: string
      visit_purpose:
        type: integer
    type: object
  core.SuccessResponse:
    properties:
      jwt:
        type: string
    type: object
  core.UserRequest:
    properties:
      nickname:
        type: string
      profile_image:
        example: base64string
        type: string
    type: object
  core.UserResponse:
    properties:
      addr:
        type: string
      addr_detail:
        type: string
      birth:
        type: string
      disable_type:
        type: integer
      email:
        type: string
      gender:
        type: boolean
      name:
        type: string
      phone:
        type: string
      username:
        type: string
      visit_purpose:
        type: integer
    type: object
  core.VerifyRequest:
    properties:
      code:
        example: 인증번호 6자리
        type: string
      phone_number:
        example: "01000000000"
        type: string
    type: object
info:
  contact: {}
paths:
  /auto-login:
    post:
      consumes:
      - application/json
      description: 최초 로그인 이후 앱 실행시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/core.AutoLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/core.SuccessResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      security:
      - jwt: []
      summary: 자동로그인
      tags:
      - 로그인 /user
  /check-username:
    get:
      consumes:
      - application/json
      description: 아이디 중복확인 시 호출
      parameters:
      - description: 중복체크 할 아이디
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 1,이미 있는 아이디 -1
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 중복확인
      tags:
      - 회원가입 /user
  /get-user:
    post:
      consumes:
      - application/json
      description: 내 정보 조회시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 유저 객체 반환
          schema:
            $ref: '#/definitions/core.UserResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 유저 조회
      tags:
      - 회원조회(본인)  /user
  /login:
    post:
      consumes:
      - application/json
      description: 아이디/비밀번호 로그인 시 호출
      parameters:
      - description: 요청 DTO
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/core.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/core.SuccessResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: -1 아이디 또는 비밀번호 불일치
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 일반로그인
      tags:
      - 로그인 /user
  /remove-profile:
    post:
      consumes:
      - application/json
      description: 기본이미지로 변경시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      security:
      - jwt: []
      summary: 프로필 사진 삭제
      tags:
      - 회원상태 변경(본인)  /user
  /remvoe-user:
    post:
      consumes:
      - application/json
      description: 회원탈퇴시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 회원탈퇴
      tags:
      - 회원탈퇴 /user
  /send-code/{number}:
    post:
      consumes:
      - application/json
      description: 휴대번호 로그인 인증번호 발송시 호출
      parameters:
      - description: 휴대번호
        in: path
        name: number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 1 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 인증번호
      tags:
      - 회원가입 /user
  /set-user:
    post:
      consumes:
      - application/json
      description: 유저 상태영구변경시 호출
      parameters:
      - description: Bearer {jwt_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 요청 DTO - 업데이트 할 데이터
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/core.UserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 200 반환
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 유저 데이터 변경
      tags:
      - 회원상태 변경(본인)  /user
  /sign-in:
    post:
      consumes:
      - application/json
      description: 회원가입 정보 입력 완료 후 호출
      parameters:
      - description: 요청 DTO
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/core.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 1, 휴대폰 인증 안함 -1
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: '요청 처리 실패시 오류 메시지 반환 '
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 회원가입
      tags:
      - 회원가입 /user
  /sns-login:
    post:
      consumes:
      - application/json
      description: sns 로그인 성공시 호출
      parameters:
      - description: 요청 DTO
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/core.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 JWT 토큰 반환
          schema:
            $ref: '#/definitions/core.SuccessResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: '요청 처리 실패시 오류 메시지 반환: 오류메시지 "-1" = 인증필요 , "-2" = 이미 가입한 번호'
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: sns 로그인
      tags:
      - 로그인 /user
  /verify-code:
    post:
      consumes:
      - application/json
      description: 인증번호 인증시 호출
      parameters:
      - description: 요청 DTO
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/core.VerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 성공시 1 반환 코드불일치 -1
          schema:
            $ref: '#/definitions/core.BasicResponse'
        "400":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
        "500":
          description: 요청 처리 실패시 오류 메시지 반환
          schema:
            $ref: '#/definitions/core.ErrorResponse'
      summary: 인증번호
      tags:
      - 회원가입 /user
swagger: "2.0"
